version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=recordbindb
    ports:
      - "5433:5432"
  web:
    stdin_open: true
    tty: true
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-backend.settings.prod}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-SecretKey}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-*}
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres@db:5432/recordbindb}
      - PORT=${PORT:-8000}
    build: .
    volumes:
      - .:/code
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    # depends_on:
    #   - db
