swagger: "2.0"
info:
  title: Record Bin
  description: Record Bin API
  contact:
    email: gui.talarico+recordbin@gmail.com
  license:
    name: MIT
  version: v1
schemes:
  - http
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  # X-API-Key: abcdef12345
  APIKeyHeader:
    type: apiKey
    in: header
    name: Authorization
  # /path?api_key=abcdef12345
  APIKeyQueryParam:
    type: apiKey
    in: query
    name: token
security:
  - APIKeyHeader: []
paths:
  /records/:
    get:
      operationId: api_v1_records_list
      description: Return a list of records.
      parameters: []
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: "#/definitions/Record"
      tags:
        - api
    post:
      operationId: api_v1_records_create
      description: Create a new record instance.
      parameters:
        - in: body
          name: record
          description: Record
          schema:
            type: object
      responses:
        "201":
          description: ""
          schema:
            $ref: "#/definitions/Record"
      tags:
        - api
  /sources/:
    get:
      operationId: api_v1_sources_list
      description: Return a list of Record Sources.
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: "#/definitions/Source"
      tags:
        - api
      parameters: []
  /tokens/:
    get:
      operationId: api_v1_tokens_list
      description: Return a list of Record Source Tokens.
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: "#/definitions/SourceToken"
      tags:
        - api
      parameters: []
definitions:
  Record:
    required:
      - data
    type: object
    properties:
      id:
        title: Id
        type: string
        format: uuid
        readOnly: true
      created_on:
        title: Created on
        type: string
        format: date-time
        readOnly: true
      data:
        title: Data
        type: string
      source:
        title: Source
        type: string
        readOnly: true
  Source:
    required:
      - name
    type: object
    properties:
      id:
        title: Id
        type: string
        format: uuid
        readOnly: true
      created_on:
        title: Created on
        type: string
        format: date-time
        readOnly: true
      name:
        title: Name
        type: string
        maxLength: 200
        minLength: 1
      owner:
        title: Owner
        type: string
        readOnly: true
  SourceToken:
    required:
      - source
    type: object
    properties:
      key:
        title: Key
        type: string
        readOnly: true
        minLength: 1
      created_on:
        title: Created on
        type: string
        format: date-time
        readOnly: true
      source:
        title: Source
        type: string
