swagger: "2.0"
info:
  title: Record Bin
  description: Record Bin API
  contact:
    email: gui.talarico+recordbin@gmail.com
  license:
    name: MIT
  version: v1
schemes:
  - http
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  # /path?api_key=abcdef12345
  AppTokenParam:
    type: apiKey
    in: query
    name: app
    description: "App Token in request url param: `/records/?token=123`"
  # Header {Authorization: Token 123...}
  AppTokenHeader:
    type: apiKey
    in: header
    name: Authorization
    description: 'App Token in request Authorization Header: `{ Authorization: "AppToken 123"}`'
  # JWT Token
  UserToken:
    type: apiKey
    in: header
    name: Authorization
    description: 'JWT Token in request Authorization Header: `{ Authorization: "Token 123"}`'
security:
  - AppTokenParam: []
  - AppTokenHeader: []
  - JwtToken: []
paths:
  /records/:
    get:
      operationId: api_v1_records_list
      description: Return a list of records.
      parameters: []
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: "#/definitions/Record"
      tags:
        - api
    post:
      operationId: api_v1_records_create
      description: Create a new record instance.
      parameters:
        - in: body
          name: record
          description: Record
          schema:
            type: object
      responses:
        "201":
          description: ""
          schema:
            $ref: "#/definitions/Record"
      tags:
        - api
  /apps/:
    get:
      operationId: api_v1_apps_list
      description: Return a list of Apps.
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: "#/definitions/App"
      tags:
        - api
      parameters: []
  /apptokens/:
    get:
      operationId: api_v1_tokens_list
      description: Return a list of Record App Tokens.
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: "#/definitions/AppToken"
      tags:
        - api
      parameters: []
definitions:
  Record:
    required:
      - data
    type: object
    properties:
      id:
        title: Id
        type: string
        format: uuid
        readOnly: true
      created_on:
        title: Created on
        type: string
        format: date-time
        readOnly: true
      data:
        title: Data
        type: string
      app:
        title: App
        type: string
        readOnly: true
  App:
    required:
      - name
    type: object
    properties:
      id:
        title: Id
        type: string
        format: uuid
        readOnly: true
      created_on:
        title: Created on
        type: string
        format: date-time
        readOnly: true
      name:
        title: Name
        type: string
        maxLength: 200
        minLength: 1
      owner:
        title: Owner
        type: string
        readOnly: true
  AppToken:
    required:
      - app
    type: object
    properties:
      key:
        title: Key
        type: string
        readOnly: true
        minLength: 1
      created_on:
        title: Created on
        type: string
        format: date-time
        readOnly: true
      app:
        title: App
        type: string
  JSONWebToken:
    required:
      - username
      - password
    type: object
    properties:
      username:
        title: Username
        type: string
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  RefreshJSONWebToken:
    required:
      - token
    type: object
    properties:
      token:
        title: Token
        type: string
        minLength: 1
  VerifyJSONWebToken:
    required:
      - token
    type: object
    properties:
      token:
        title: Token
        type: string
        minLength: 1
