# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
        environment:
          PIPENV_VENV_IN_PROJECT: 1
          PIPENV_QUIET: 1
          DATABASE_URL: postgresql://root@localhost/circle_test
          CODECOV_TOKEN: XXX

      # Service container image available at `host: localhost`
      - image: circleci/postgres:9.6.2-alpine
        # environment:
        #   POSTGRES_USER: postgres
        #   POSTGRES_DB: recordbindb
        #   PG_HOST: db

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade --quiet pip
            pip install --quiet pipenv
            pipenv install --dev --deploy

      - save_cache:
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - ./venv

      - run:
          name: prepare database
          command: |
            . venv/bin/activate
            python manage.py collectstatic --noinput -v=0
            python manage.py migrate
            python manage.py seed

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest
      # - run:
      #     name: run linter
      #     command: |
      #       . venv/bin/activate
      #       flake8 .
      # - run:
      #     name: upload coverage report
      #     command: |
      #       . venv/bin/activate
      #       pip install codecov
      #       codecov -t "$CODECOV_TOKEN"
